projects:
  My Budget X App AppSync API:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: jszxj4exlnc2lf4ptpuzhvwd6a
        maxDepth: 2
extensions:
  amplify:
    version: 3
